_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: "50x"
  HEADS:
    IN_FEAT: 2048

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/market1501/sbs_R50"