_BASE_: "../Base-Strongerbaseline.yml"

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

MODEL:
  BACKBONE:
    WITH_NL: False
    NAME: "build_osnet_backbone"
    DEPTH: "x1_0"
  HEADS:
    IN_FEAT: 512

OUTPUT_DIR: "logs/market1501/sbs_OS50"
